import { RiceProduct } from "./types";

export const RICE_PRODUCTS: RiceProduct[] = [
  {
    id: "sona-masoori-unpolished",
    name: "Unpolished Sona Masoori Rice",
    nativeName: "સોના મસુરી",
    tagline:
      "Lightweight, naturally aged daily grain with a low glycemic index",
    category: "daily",
    pricePerKg: 85,
    discountedPricePerKg: 76,
    availableWeights: [1, 5, 10, 25],
    grainType: "Medium",
    processing: "Unpolished",
    aromaLevel: 2,
    giIndex: "Low (<55)",
    agingMonths: 12,
    originRegion: "Koppal, Karnataka & Tungabhadra Belt",
    originState: "Karnataka",
    harvestDate: "2024-10-15",
    cookTimeMins: 15,
    waterRatio: "1 : 2.5",
    description:
      "Directly sourced from organic paddy farms in Karnataka. Unpolished to preserve the natural bran layer rich in dietary fiber, B-vitamins, and minerals. Exceptionally light on digestion.",
    bestFor: ["Daily Meals", "Sambar Rice", "Curd Rice", "Khichdi", "Lemon Rice"],
    badges: ["100% Organic", "Low GI", "Unpolished Bran", "Pesticide Free"],
    stockKg: 1200,
    rating: 4.8,
    reviewsCount: 342,
    image:
      "/rice/sona-masoori.jpg",
    nutritionFacts: {
      caloriesPer100g: 350,
      carbsGrams: 77,
      proteinGrams: 8.5,
      fiberGrams: 3.8,
      glycemicIndexValue: 51,
    },
    farmingMethod:
      "Zero-Budget Natural Farming (ZBNF) using Jeevamrutha and Neem Oil spray.",
  },
  {
    id: "indrayani-aromatic",
    name: "Indrayani Fragrant Rice",
    nativeName: "इंद्रायणी तांदूळ",
    tagline: "Aromatic, soft-melting heritage grain of Western Maharashtra",
    category: "heritage",
    pricePerKg: 95,
    discountedPricePerKg: 88,
    availableWeights: [1, 5, 10, 25],
    grainType: "Medium",
    processing: "Raw",
    aromaLevel: 4,
    giIndex: "Medium (55-69)",
    agingMonths: 9,
    originRegion: "Maval & Pune Valley, Maharashtra",
    originState: "Maharashtra",
    harvestDate: "2024-11-20",
    cookTimeMins: 18,
    waterRatio: "1 : 2.8",
    description:
      "Renowned for its heavenly floral aroma and delightfully sticky, soft texture when cooked. Perfect for traditional Varan Bhaat, Masale Bhaat, and soul-soothing Khichdi.",
    bestFor: ["Varan Bhaat", "Masale Bhaat", "Khichdi", "Puran Bhaat", "Porridge"],
    badges: ["Heritage Scented", "Farm Direct", "GI Tagged Region"],
    stockKg: 850,
    rating: 4.9,
    reviewsCount: 518,
    image:
      "/rice/indrayani.jpg",
    nutritionFacts: {
      caloriesPer100g: 356,
      carbsGrams: 78,
      proteinGrams: 7.2,
      fiberGrams: 2.1,
      glycemicIndexValue: 58,
    },
    farmingMethod: "Rainfed hill cultivation using indigenous heirloom seeds.",
  },
  {
    id: "1121-steam-basmati",
    name: "Royal 1121 Extra Long Steam Basmati",
    nativeName: "शाही बास्मती ११२१",
    tagline: "Crown jewel of Basmati with 24mm cooked grain elongation",
    category: "aromatic",
    pricePerKg: 190,
    discountedPricePerKg: 168,
    availableWeights: [1, 5, 10, 25],
    grainType: "Extra Long",
    processing: "Steamed",
    aromaLevel: 5,
    giIndex: "Medium (55-69)",
    agingMonths: 24,
    originRegion: "Tarori & Karnal, Haryana",
    originState: "Punjab",
    harvestDate: "2024-10-08",
    cookTimeMins: 12,
    waterRatio: "1 : 2.0",
    description:
      "Aged for 2 full years in traditional grain granaries. Each grain cooks into a slender, non-sticky masterpiece that expands to twice its raw length. Scented with natural 2-acetyl-1-pyrroline.",
    bestFor: ["Dum Biryani", "Shahi Pulao", "Fried Rice", "Jeera Rice", "Ghee Rice"],
    badges: ["Aged 24 Months", "24mm Elongation", "Export Grade A+"],
    stockKg: 2000,
    rating: 4.9,
    reviewsCount: 890,
    image:
      "/rice/basmati-1121.jpg",
    nutritionFacts: {
      caloriesPer100g: 348,
      carbsGrams: 76,
      proteinGrams: 8.9,
      fiberGrams: 1.8,
      glycemicIndexValue: 56,
    },
    farmingMethod: "Himalayan snowfed water irrigated paddy fields.",
  },
  {
    id: "black-rice-karuppu-kavuni",
    name: "Karuppu Kavuni Organic Black Rice",
    nativeName: "கருப்பு கவுனி அரிசி",
    tagline: "Ancient Forbidden Superfood rich in Anthocyanin antioxidants",
    category: "superfood",
    pricePerKg: 240,
    discountedPricePerKg: 215,
    availableWeights: [1, 5, 10],
    grainType: "Medium",
    processing: "Unpolished",
    aromaLevel: 3,
    giIndex: "Low (<55)",
    agingMonths: 6,
    originRegion: "Chettinad & Madurai, Tamil Nadu",
    originState: "Tamil Nadu",
    harvestDate: "2024-09-25",
    cookTimeMins: 35,
    waterRatio: "1 : 3.5",
    description:
      "Historically reserved for royalty. Packed with powerful antioxidants (anthocyanins), iron, and fiber. Deep purple-black hue that delivers a nutty flavor and chewy texture.",
    bestFor: [
      "Black Rice Porridge",
      "Kavuni Arisi Sweet",
      "Superfood Salad",
      "Fitness Bowls",
      "Kheer",
    ],
    badges: ["Ancient Superfood", "Low GI (42)", "Rich in Iron & Fiber", "Anti-Diabetic"],
    stockKg: 600,
    rating: 4.9,
    reviewsCount: 275,
    image:
      "/rice/black-kavuni.jpg",
    nutritionFacts: {
      caloriesPer100g: 340,
      carbsGrams: 72,
      proteinGrams: 9.8,
      fiberGrams: 5.2,
      glycemicIndexValue: 42,
    },
    farmingMethod:
      "Traditional organic natural farming with native bio-fertilizers.",
  },
  {
    id: "rajamudi-heritage",
    name: "Rajamudi Heritage Unpolished Rice",
    nativeName: "ರಾಜಮುಡಿ ಅಕ್ಕಿ",
    tagline: "Royal heirloom grain of the Mysuru Maharajas with high zinc & iron",
    category: "heritage",
    pricePerKg: 130,
    discountedPricePerKg: 118,
    availableWeights: [1, 5, 10, 25],
    grainType: "Medium",
    processing: "Unpolished",
    aromaLevel: 3,
    giIndex: "Low (<55)",
    agingMonths: 12,
    originRegion: "Hassan & Mandya, Karnataka",
    originState: "Karnataka",
    harvestDate: "2024-11-10",
    cookTimeMins: 22,
    waterRatio: "1 : 2.8",
    description:
      "A prized red-and-white striped heirloom grain cultivated since the 17th century under Wodeyar patronage. Exceptionally nutrient-dense, promoting immunity and bone strength.",
    bestFor: ["Daily Meals", "Bisibelebath", "Health Bowls", "Dosa Batter", "Porridge"],
    badges: ["Royal Heirloom", "Immunity Booster", "Rich in Zinc"],
    stockKg: 950,
    rating: 4.8,
    reviewsCount: 184,
    image:
      "/rice/rajamudi.jpg",
    nutritionFacts: {
      caloriesPer100g: 345,
      carbsGrams: 74,
      proteinGrams: 8.2,
      fiberGrams: 4.1,
      glycemicIndexValue: 52,
    },
    farmingMethod:
      "Indigenous SRI (System of Rice Intensification) water-saving technique.",
  },
  {
    id: "kerala-matta-red",
    name: "Palakkad Matta Red Parboiled Rice",
    nativeName: "പാലക്കാടൻ മട്ട അരി",
    tagline: "Bold red pericarp grain packed with natural nutrients and fiber",
    category: "heritage",
    pricePerKg: 90,
    discountedPricePerKg: 82,
    availableWeights: [1, 5, 10, 25],
    grainType: "Short",
    processing: "Parboiled",
    aromaLevel: 2,
    giIndex: "Low (<55)",
    agingMonths: 10,
    originRegion: "Palakkad Gap, Kerala",
    originState: "Kerala",
    harvestDate: "2024-12-05",
    cookTimeMins: 25,
    waterRatio: "1 : 3.5",
    description:
      "Distinctive thick red grain with a robust earthy taste. Double-parboiled with husk intact to retain essential minerals, Vitamin B6, and complex carbohydrates for sustained energy.",
    bestFor: ["Kerala Fish Curry Meals", "Kanji (Porridge)", "Sambar Bhaat", "Idli & Dosa"],
    badges: ["GI Protected", "Double Parboiled", "Heart Healthy"],
    stockKg: 1100,
    rating: 4.7,
    reviewsCount: 310,
    image:
      "/rice/matta-red.jpg",
    nutritionFacts: {
      caloriesPer100g: 338,
      carbsGrams: 73,
      proteinGrams: 7.9,
      fiberGrams: 4.5,
      glycemicIndexValue: 50,
    },
    farmingMethod: "Traditional canal-irrigated black soil organic paddy farming.",
  },
  {
    id: "gobindobhog-aromatic",
    name: "Gobindobhog Sweet Aromatic Rice",
    nativeName: "গোবিন্দভোগ চাল",
    tagline: "Divine buttery fragrance, Bengal's prized short-grain bhog offering",
    category: "aromatic",
    pricePerKg: 160,
    discountedPricePerKg: 145,
    availableWeights: [1, 5, 10],
    grainType: "Short",
    processing: "Raw",
    aromaLevel: 5,
    giIndex: "Medium (55-69)",
    agingMonths: 12,
    originRegion: "Burdwan & Hooghly, West Bengal",
    originState: "West Bengal",
    harvestDate: "2024-11-15",
    cookTimeMins: 15,
    waterRatio: "1 : 2.2",
    description:
      "Traditionally offered to Lord Krishna in temples. Short, plump white grains infused with a natural ghee-like aroma and rich flavor that turns any dish into a festive celebration.",
    bestFor: ["Payesh / Kheer", "Bengali Pulao", "Khichuri", "Bhog", "Firni"],
    badges: ["GI Tagged", "Pure Ghee Aroma", "Temple Bhog Quality"],
    stockKg: 700,
    rating: 4.9,
    reviewsCount: 420,
    image:
      "/rice/gobindobhog.jpg",
    nutritionFacts: {
      caloriesPer100g: 358,
      carbsGrams: 79,
      proteinGrams: 7.0,
      fiberGrams: 1.5,
      glycemicIndexValue: 62,
    },
    farmingMethod: "Gangetic alluvial plane natural organic cultivation.",
  },
  {
    id: "wada-kolam-soft",
    name: "Surti Wada Kolam Rice",
    nativeName: "વાડા કોલમ",
    tagline: "Ultra-soft everyday white grain with effortless digestion",
    category: "daily",
    pricePerKg: 78,
    discountedPricePerKg: 72,
    availableWeights: [1, 5, 10, 25],
    grainType: "Medium",
    processing: "Raw",
    aromaLevel: 2,
    giIndex: "Medium (55-69)",
    agingMonths: 12,
    originRegion: "Wada, Palghar & South Gujarat",
    originState: "Maharashtra",
    harvestDate: "2024-10-28",
    cookTimeMins: 14,
    waterRatio: "1 : 2.4",
    description:
      "Tiny, smooth white grains that cook fluffy and remain tender all day long. A beloved household classic for daily lunches, dal chawal, and gentle light meals.",
    bestFor: ["Dal Chawal", "Curd Rice", "Light Khichdi", "Pulao"],
    badges: ["Daily Choice", "Easy Digestion", "Family Value"],
    stockKg: 1500,
    rating: 4.8,
    reviewsCount: 630,
    image:
      "/rice/wada-kolam.jpg",
    nutritionFacts: {
      caloriesPer100g: 352,
      carbsGrams: 78,
      proteinGrams: 7.5,
      fiberGrams: 2.0,
      glycemicIndexValue: 60,
    },
    farmingMethod: "Sub-mountainous soil cultivation with minimal natural inputs.",
  },
  {
    id: "ambemohar-scented",
    name: "Ambemohar Mango Blossom Rice",
    nativeName: "आंबेमोहर तांदूळ",
    tagline: "Captivating fragrance reminiscent of sweet mango blossoms",
    category: "aromatic",
    pricePerKg: 175,
    discountedPricePerKg: 155,
    availableWeights: [1, 5, 10],
    grainType: "Short",
    processing: "Raw",
    aromaLevel: 5,
    giIndex: "Medium (55-69)",
    agingMonths: 12,
    originRegion: "Western Ghats, Maharashtra",
    originState: "Maharashtra",
    harvestDate: "2024-11-22",
    cookTimeMins: 16,
    waterRatio: "1 : 2.5",
    description:
      "An ancient scented short-grain rice that releases an intoxicating natural aroma during boiling. Soft, comforting, and easily digestible, favored for baby food and festive feasts.",
    bestFor: ["Sweet Kheer", "Varan Bhaat", "Baby Cereal", "Festive Meals"],
    badges: ["Rare Heritage", "Mango Scent", "Ultra Soft"],
    stockKg: 500,
    rating: 4.9,
    reviewsCount: 290,
    image:
      "/rice/ambemohar.jpg",
    nutritionFacts: {
      caloriesPer100g: 355,
      carbsGrams: 77,
      proteinGrams: 7.8,
      fiberGrams: 2.2,
      glycemicIndexValue: 59,
    },
    farmingMethod:
      "High altitude Sahyadri terraced farming with mountain spring water.",
  },
  {
    id: "organic-trio-combo",
    name: "Heritage Grain Trio Organic Bundle (15kg)",
    nativeName: "ઑર્ગેનિક ત્રીઓ બંડલ",
    tagline: "Curated 3-bag combo: 5kg Rajamudi + 5kg Black Rice + 5kg Indrayani",
    category: "combos",
    pricePerKg: 155,
    discountedPricePerKg: 130,
    availableWeights: [15],
    grainType: "Medium",
    processing: "Unpolished",
    aromaLevel: 4,
    giIndex: "Low (<55)",
    agingMonths: 12,
    originRegion: "Multi-State Farmer Cooperative",
    originState: "Karnataka",
    harvestDate: "2024-10-15",
    cookTimeMins: 18,
    waterRatio: "Varies by grain",
    description:
      "Experience the best of ancient Indian rice diversity! Contains 5kg Organic Black Rice (antioxidant power), 5kg Rajamudi Unpolished (iron & zinc), and 5kg Indrayani Aromatic (comfort meal). Save 18% over individual purchases.",
    bestFor: ["Weekly Rotation", "Family Wellness", "Gifting", "Balanced Diet"],
    badges: ["Best Value Combo", "18% Off", "Multi-Grain Variety"],
    stockKg: 400,
    rating: 5.0,
    reviewsCount: 156,
    image:
      "/rice/trio-combo.jpg",
    nutritionFacts: {
      caloriesPer100g: 345,
      carbsGrams: 74,
      proteinGrams: 8.8,
      fiberGrams: 4.2,
      glycemicIndexValue: 48,
    },
    farmingMethod: "100% Certified Organic Farmer Producer Organization (FPO).",
  },
];

export const CATEGORIES = [
  { id: "all", label: "All Grain Varieties", short: "All Varieties" },
  { id: "daily", label: "Daily Staples", short: "Daily Staples" },
  { id: "heritage", label: "Heritage & Unpolished", short: "Heritage" },
  { id: "aromatic", label: "Aromatic & Basmati", short: "Aromatic" },
  { id: "superfood", label: "Diabetic & Low GI", short: "Low GI" },
  { id: "combos", label: "Value Bundles", short: "Bundles" },
] as const;

export function getPriceForWeight(
  product: RiceProduct,
  weightKg: number
): { final: number; original: number; savings: number; perKg: number } {
  const base = product.discountedPricePerKg ?? product.pricePerKg;
  let multiplier = 1;
  if (weightKg === 10) multiplier = 0.95;
  if (weightKg === 25) multiplier = 0.9;
  const perKg = Math.round(base * multiplier);
  const final = Math.round(perKg * weightKg);
  const original = product.pricePerKg * weightKg;
  return { final, original, savings: original - final, perKg };
}
